spring:
  rabbitmq:
    host: 192.168.123.176
    port: 5672
  application:
    name: expenses-catalog-servers
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
