keycloak:
  realm: expenses
  resource: expenses-app
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://192.168.123.157:3306/accountsdb?useSSL=false
    username: spring
    password: expenses
    driverClassName: com.mysql.jdbc.Driver
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
logging:
  file: myapplication.log
server:
  port: 8380
account:
  messaging:
    exchange: eventExchange
    transactionServiceQueue: transactionProcessedServiceQueue