keycloak:
  auth-server-url: https://security.eimantas-services.de/auth
  realm: expenses
  resource: expenses-app
  public-client: true
  principal-attribute: preferred_username
spring:
  rabbitmq:
    host: 192.168.123.176
    port: 5672
  application:
    name: expenses-catalog-servers
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
